### ISSUE TITLE
session exipre

### ISSUE THREAD

**Issue by ymmedia** [kaltura/KalturaGeneratedAPIClientsNodeJS#16]
hello,

How to check if a session is expiring.

Is it necessary to do a service.session.start at each request?

Or do services.session.start once is checked to see if it is expiring?

Thank you in advance for your answer.

ymmedia.

**Comment by kaltura-hooks** [comment]
Hi @ymmedia,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi @ymmedia,

When calling session.start(), the fifth parameter is "expiry", if not set, the default expiry is 86,400 seconds or, 24 hours. 
Thus, there is absolutely no need to call session.start() before each request. You should generate a KS [Kaltura Session] once, set the desired expiry and call client.setKs(ks) where ks is the value returned from session.start().
If you wish to invalidate a KS  before the expiry time was reached, you can call session.end().
To extract the values of a given KS [sessionType, partnerId, userId, expiry, privileges] you may use session.get().

For more info about using the API see:
https://developer.kaltura.com

And in particular to session:
https://developer.kaltura.com/api-docs/Generate_API_Sessions/session
https://developer.kaltura.com/workflows/Generate_API_Sessions/Authentication

**Comment by ymmedia** [comment]
thank you for your reply 👍
