### ISSUE TITLE
Kaltura entry not created with different language

### ISSUE THREAD

**Issue by AsifShaafi** [kaltura/KalturaGeneratedAPIClientsNodeJS#18]
I tried to create a Kaltura base entry with the title: _**Bilraes på Graabroedre Plads skal _forhindres**_. But when I run the program, it gives me an error. 

Here is the code I'm using:

``` javascript
  const mediaEntry = new kaltura.objects.MediaEntry();
  mediaEntry.name = 'Bilraes på Graabroedre Plads skal _forhindres';
  mediaEntry.description = 'Test description';
  mediaEntry.tags = '';
  mediaEntry.mediaType = kaltura.enums.MediaType.VIDEO;

  const entry = await kaltura.services.media.add(mediaEntry).execute(client);
  return entry;

```

And this is the JSON that's been created and showed in the console:

``` JSON
{
   "entry":{
      "objectType":"KalturaMediaEntry",
      "name":"Bilraes på Graabroedre Plads skal _forhindres",
      "description":"Test description",
      "tags":"",
      "mediaType":1
   },
   "format":1,
   "apiVersion":"15.17.0",
   "clientTag":"node:20-02-17",
   "ks":"djJ8MjcwNTIzMXy-D27pb8dtW19InhN1LmGvUTL7wLZKsGG6Zn7bdUx61orNCwI751m_lyQni2dv4tjIGlO3guv1aFe9v5pmL5zs8fPbQq971lCbrezgmTRcwBEXWNoWi8ZvvxVtiBOV_F8=",
   "kalsig":"0cecba5c8acd1bd2decb5f96bf110c49"
}
```

And the error output:

``` xml
<?xml version="1.0" encoding="utf-8"?><xml><result><error><objectType>KalturaAPIException</objectType><code>MISSING_MANDATORY_PARAMETER</code><message>Missing parameter &quot;entry&quot;</message><args><item><objectType>KalturaApiExceptionArg</objectType><name>PARAM_NAME</name><value>entry</value></item></args></error></result><executionTime>0.001910924911499</executionTime></xml>
```

Here it says, `Missing parameter entry`, but you can see the entry is there in the created JSON. 

This same code works fine with a normal test.

N.B.: I'm working on windows machine. And the code is being used in a *NodeJs* project. I'm using the _*[kaltura-client](https://www.npmjs.com/package/kaltura-client)*_ npm library, version **16.2.0**. I used the library using `npm i kaltura-client` command from cmd.

Windows version: windows 10
node version: v10.16.3
npm version: 6.9.0
kaltura-client version: 16.2.0

**Comment by kaltura-hooks** [comment]
Hi @AsifShaafi,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by andrewchart** [comment]
**+1 for this issue.** The use of certain characters in the `name` or `description` fields e.g. emoji causes this error, specifically with the Node.js client. Using `kaltura.services.media.update` ...

```
MediaEntry {
  objectType: 'KalturaMediaEntry',
  mediaType: 1,
  name: '5fd9e8aa7ba3cb0018b0ecc8👍',
  description: 'Honor12345',
  tags: '',
  partnerSortValue: 18622
}
```
Results in
```
<?xml version="1.0" encoding="utf-8"?><xml><result><error><code>MISSING_MANDATORY_PARAMETER</code><message>Missing parameter &quot;entryId&quot;</message><objectType>KalturaAPIException</objectType><args><item><objectType>KalturaApiExceptionArg</objectType><name>PARAM_NAME</name><value>entryId</value></item></args></error></result><executionTime>0.0011088848114014</executionTime></xml>
```

If I remove the `👍`  character, the entry updates successfully. I have found many accented characters e.g. `é` will cause the same error. 

Kaltura Client Version: `16.5.0`

**Comment by andrewchart** [comment]
I have investigated this further and believe I understand the issue to some degree. It arises because the Kaltura client contains this code:

https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/blob/fb3a1f2c82e730abf430a68154702acaf3f5cae7/KalturaClientBase.js#L314

Counting the length of the body and therefore the `Content-Length` header using `str.length` is insufficient. This is because str.length [counts code points, not characters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length#unicode). 

The `Content-Length` header should specify [the **byte** length of the content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length).

If you comment out the line which explicitly declares the value of the Content-Length header, the `request` library calculates a _different_ content length. See below. I logged out the headers and body of the `Request` object.

```
//With line #314 in the code...
headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
    'Content-Length': 445,
    host: 'platform.vixyvideo.com'
},
body: '{"entryId":"0_vvbv2n4g","mediaEntry":{"objectType":"KalturaMediaEntry","mediaType":1,"name":"5fd9e8aa7ba3cb0018b0ecc8abcd🆒🆒🆒","description":"Honor12345","tags":"","partnerSortValue":18622},"format":1,"apiVersion":"16.5.0","clientTag":"node:20-06-29","ks":"xxxxx","kalsig":"xxxxx"}'


//With line #314 commented out
headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
    host: 'platform.vixyvideo.com',
    'content-length': 451
},
body: '{"entryId":"0_vvbv2n4g","mediaEntry":{"objectType":"KalturaMediaEntry","mediaType":1,"name":"5fd9e8aa7ba3cb0018b0ecc8abcd🆒🆒🆒","description":"Honor12345","tags":"","partnerSortValue":18622},"format":1,"apiVersion":"16.5.0","clientTag":"node:20-06-29","ks":"xxxxx","kalsig":"xxxxx"}'
```

Notice that the content length header is calculated as `445` in the first instance, but `451` in the second instance. 

**The first request fails, whereas the second one succeeds.** The only difference is the `Content-Length` header, and I believe the server is erroring in the first response because the body length in bytes does not match the `Content-Length` header.

### Solutions?

1. A simple solution might be to simply remove this line, and allow the `request` library to calculate the `Content-Length` header. I do not have the knowledge of the library to test this extensively, but I can say that, within my project, I have found this sufficient in order to use the `media.update` and `media.add` services with no further errors.

2. Alternatively, if it is important to specify the `Content-Length` header from within the Kaltura client, the length should be calculated by processing the string in such a way that the bytes are counted. I looked into how `request` does this. They use `Buffer` (from the `safe-buffer` package but it also works with the Node global `Buffer` API):

https://github.com/request/request/blob/3c0cddc7c8eb60b470e9519da85896ed7ee0081e/request.js#L424-L432

Indeed, if I use this code in place of line #314, I get the correct byte length of the content, and the issue appears to be solved. 

```
//options.headers['Content-Length'] = body.length;
		
let bodyLength;
if (typeof body === 'string') {
    bodyLength = Buffer.byteLength(body);
} else if (Array.isArray(body)) {
    bodyLength = body.reduce(function (a, b) { return a + b.length }, 0);
} else {
    bodyLength = body.length;
}

options.headers['Content-Length'] = bodyLength;
```

However, if there is no good reason to do this, commenting out the code in the Kaltura Node client and leaving the byte calculation to the lower-level library seems sensible, in my opinion.

~~I will look into creating a Pull Request for this, and consider if this should be done against this repo or against the Client Generator repo.~~

---

**EDIT: I have realised that this issue is already well reported within the client generator repo and there are existing PRs. Links below for reference. I hope this helps someone.**

* https://github.com/kaltura/clients-generator/issues/568
* https://github.com/kaltura/clients-generator/pull/518
* https://github.com/kaltura/clients-generator/pull/536

**Comment by jessp01** [comment]
This was address here: https://github.com/kaltura/clients-generator/pull/518
