### ISSUE TITLE
Potential exposure to CVE-2021-3918 - Score 9.8

### ISSUE THREAD

**Issue by felix-hcl** [kaltura/KalturaGeneratedAPIClientsNodeJS#21]
## Steps to reproduce

1. Install kaltura-client
2. run `npm ls json-schema`

## Current Behavior

The vulnerable version of json-schema is a sub-dependency of `request@2.88.2` which is the latest version of the deprecated http client.
```
└─┬ kaltura-client@17.14.0
  └─┬ request@2.88.2
    └─┬ http-signature@1.2.0
      └─┬ jsprim@1.4.1
        └── json-schema@0.2.3 
 ```

## Expected Behavior

Usage of non-deprectated package which are not exposed to security vulnerabilities.

## Additional information
https://nvd.nist.gov/vuln/detail/CVE-2021-3918
Fixes exist for `json-schema`, `jsprim` and `http-signature` but `request` does not accept `http-signature@1.3.6` which would resolve this issue:
https://github.com/joyent/node-http-signature/blob/master/CHANGES.md#136

**Comment by kaltura-hooks** [comment]
Hi @felix-hcl,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi @felix-hcl ,

Thank you for your report.
Please see https://github.com/kaltura/clients-generator/pull/733/files

A new NPM package (17.18.2) was pushed to https://www.npmjs.com/package/kaltura-client.
