### ISSUE TITLE
toParams is not defined

### ISSUE THREAD

**Issue by avrono** [kaltura/KalturaGeneratedAPIClientsNodeJS#3]
I am trying to use the code snippet provided, but get the above error

var Kaltura = require('./lib/KalturaClient.js');
var config = new Kaltura.KalturaConfiguration(xxxxxxxx);
config.serviceUrl = "https://www.kaltura.com/";
var client = new Kaltura.KalturaClient(config);
client.session.start(function(ks) {
  if (ks.code && ks.message) {
    console.log('Error starting session', success, ks);
  } else {
    client.setKs(ks);
  }
}, "xxxxxxxxxxxxxxxxxxxxxx",
"xxxx@xxxxxxx.com",
Kaltura.enums.KalturaSessionType.ADMIN,
xxxxxx)

**Comment by kaltura-hooks** [comment]
Hi @avrono,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa "kaltura*"
```

```
For deb based systems:
```

```
    # dpkg -l "kaltura-*"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi,

The code you posted works fine for me with my partner.
Can you please attach the full trace?

**Comment by jessp01** [comment]
Closing in favour of http://forum.kaltura.org/t/nodejs-and-kaltura-api/3810/4.

**Comment by avrono** [comment]
<!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/stylesheets/style.css"></head><body><h1>toParams is not defined</h1><h2></h2><pre>ReferenceError: toParams is not defined
    at Object.&lt;anonymous&gt; (/home/avrono/workspace/knowledgemotion/km-api/KalturaGeneratedAPIClientsNodeJS/KalturaClientBase.js:124:36)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.&lt;anonymous&gt; (/home/avrono/workspace/knowledgemotion/km-api/KalturaGeneratedAPIClientsNodeJS/KalturaClient.js:33:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)</pre></body></html>

**Comment by jessp01** [comment]
I think you may be missing some supporting modules.
I suggest you install the npm from https://www.npmjs.com/package/kaltura
and then, if it still does not work, debug by running a simple snippet from CLI like so:
$ nodejs /path/to/snippet.js
