### ISSUE TITLE
Missing Request Parameters 

### ISSUE THREAD

**Issue by jonfackrell** [kaltura/KalturaGeneratedAPIClientsNodeJS#4]
I starting working with the node.js client api client and found what appears to be a bug. I am tryng to upload a video, but after I get an uploadTokenId, it is not added to the request. You can see in the attached screenshot that data is being appended to the requestUrl before it is set and the params are never added to the options. So the uploadTokenId is never added to the request.

On the same note, the format is not added so the repsonse (in this case an error) is coming back as XML, which the client is not expecting.

![kaltura-bug](https://cloud.githubusercontent.com/assets/2992230/12158580/6068d2e4-b498-11e5-9c49-8de83661da18.jpg)

**Comment by kaltura-hooks** [comment]
Hi @jonfackrell,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa "kaltura*"
```

```
For deb based systems:
```

```
    # dpkg -l "kaltura-*"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by tan-tan-kanarek** [comment]
Hi @jonfackrell, 
You're right, file upload is not well implemented in this client lib.

**Comment by jessp01** [comment]
Hi @jonfackrell,

While it should definitely be fixed, please see:
https://developer.kaltura.org/recipes/upload

If you choose NodeJS as the language, you will see a working implementation that uses http://kaltura.github.io/jQuery-File-Upload/ to achieve a successful upload.
The jQuery-File-Upload also supports chunk uploads, which is necessary when uploading files bigger than 2G.

Thanks,

**Comment by jessp01** [comment]
Closing this one post my last reply.
