### ISSUE TITLE
Npm package is broken

### ISSUE THREAD

**Issue by CodeJjang** [kaltura/KalturaGeneratedAPIClientsNodeJS#5]
Hello,

The npm version of this module is broken.
First, after editing the test.js file and running it I found out that the 'config.js' file was missing.
I then added it, re-run the test but now I get this error:

undefined:1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/.../node_modules/kaltura/KalturaClientBase.js:389:28)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

In the same time, it would be really nice if you added more code samples of how to use the node js client as it is quite messy. Thanks.

**Comment by kaltura-hooks** [comment]
Hi @CodeJjang,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa \"kaltura*\"
```

```
For deb based systems:
```

```
    # dpkg -l \"kaltura-*\"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by CodeJjang** [comment]
Ok i think I got it. The test expects the API to respond with json format answer, while the default answer is JSON, so it fails on the JSON.parse(data) line in the KalturaClientBase class.

However, I can't find where to change the behaviour of the client class to expect XML instead or JSON, or how to add to the request parameters to ask for JSON format and not the default XML one.

**Comment by CodeJjang** [comment]
I printed the KalturaConfiguration object:

{ serviceUrl: 'http://vod.linnovate.net',
  serviceBase: '/api_v3/service',
  format: 1,
  timeout: 90000,
  logger: null }

format:1 means JSON, but for some reason the API ignores the format parameter and  returns XML...

**Comment by CodeJjang** [comment]
Ok it was my problem, but your NPM package (named kaltura) is missing config.js file...

**Comment by prabjot678** [comment]
@CodeJjang  Can you please help me,issue reported here, http://stackoverflow.com/questions/38056867/nodejspath-must-be-a-string-without-null-bytes?noredirect=1#comment63553738_38056867
