### ISSUE TITLE
Npm package 'kaltura' missing config.js

### ISSUE THREAD

**Issue by CodeJjang** [kaltura/KalturaGeneratedAPIClientsNodeJS#6]
Hello Kaltura staff,

Your npm package named 'kaltura' is missing the config.js file.
Thus, anyone who performs a 'npm install' has to manually add an empty config.js file, else the server won't lift.

I believe this is a bug.

CodeJjang

**Comment by kaltura-hooks** [comment]
Hi @CodeJjang,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa \"kaltura*\"
```

```
For deb based systems:
```

```
    # dpkg -l \"kaltura-*\"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by tan-tan-kanarek** [comment]
Of course we can't generate a configuration file with the user credentials, but we can improve the error message to inform that the configuration file is missing, we will do that.

**Comment by CodeJjang** [comment]
The user credentials are given to the KalturaClient object as parameters anyway, and are handled in the global configuration of the app itself.
I don't see why a package should require the users to keep the credentials inside it's internals...
What happens is, I have to add a blank config.js file, and so does anyone who calls 'npm install' on my app because of that.

**Comment by tan-tan-kanarek** [comment]
I agree, we will take care of that.

**Comment by tlt-zbynek** [comment]
Hi,
that would be nice, as of now this is not ready for production deployment,
thanks,
Z.

**Comment by tan-tan-kanarek** [comment]
I don't see how the lack of the configuration file prevent the npm install.
The configuration file is needed in order to run kaltura client tests, which you don't need.

**Comment by jessp01** [comment]
Hi,

This should be resolved with the latest 'kaltura' npm version. 
Please upgrade to it and if you're still having issues, post them at forum.kaltura.org and I'll be happy to take a look.
Thanks,
