### ISSUE TITLE
Getting started guide?

### ISSUE THREAD

**Issue by theisof** [kaltura/KalturaGeneratedAPIClientsNodeJS#7]
Is there a getting started guide or tutorial somewhere for this Node library? 

Came across [this link](https://knowledge.kaltura.com/introduction-kaltura-client-libraries#GeneratingaClientLibraryoaLocalServer), but there aren't any Node examples(?)

**Comment by kaltura-hooks** [comment]
Hi @theisof,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa \"kaltura*\"
```

```
For deb based systems:
```

```
    # dpkg -l \"kaltura-*\"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by tan-tan-kanarek** [comment]
Unfortunately, there is no guide at the moment, but you can see few projects that implemented base on this lib:
- https://github.com/kaltura/play-server
- https://github.com/kaltura/ftp-api-server

**Comment by theisof** [comment]
Thanks. Got it working with Express like this :

```
// index.js
import express from 'express'
import { session } from './session'

const router = express.Router()

router.route('/media')
  .get((req, res) => {
    session(function(client){
      client.media.listAction(function(data){
        res.status(200).send({ data }).end()
      })
    })
 })

router.route('/media/:id*')
  .get((req, res) => {
    session(function(client){
      client.media.get(function(data){
        res.status(200).send({ data }).end()
      }, req.param('id'))
    })
 })

export default router

// session.js
import { secret, partnerId, userId } from './secrets' 
import kc from '../lib/kaltura/KalturaClient'
import ktypes from '../lib/kaltura/KalturaTypes'

const serviceUrl = "http://www.kaltura.com"
const expiry = 100000
const privileges = null

export function session (callback) {
  let conf = new kc.KalturaConfiguration(partnerId)
  conf.serviceUrl = serviceUrl

  let client = new kc.KalturaClient(conf)
  let type = ktypes.KalturaSessionType.ADMIN

  client.session.start(function (result) {
    client.setKs(result)
    callback(client)
  }, secret, userId, type, partnerId, expiry, privileges)
}
```

Also had to change KalturaClientBase like this: https://github.com/kaltura/server/pull/3476/files
