### ISSUE TITLE
Path must be a string without null bytes

### ISSUE THREAD

**Issue by prabjot678** [kaltura/KalturaGeneratedAPIClientsNodeJS#8]
I am facing error "Path must be a string without null bytes", while uploading files into kaltura. you can find full details at 

stackoverflow.com/questions/38056867/nodejspath-must-be-a-string-without-null-bytes?noredirect=1#comment63553738_38056867

**Comment by kaltura-hooks** [comment]
Hi @prabjot678,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa \"kaltura*\"
```

```
For deb based systems:
```

```
    # dpkg -l \"kaltura-*\"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by prabjot678** [comment]
I am just using npm package kaltura and i am facing this error consistently.
So can you tell me please what i am doing wrong here ?

Thanks

On Mon, Jun 27, 2016 at 11:40 PM, Kaltura GitHub Hooks <
notifications@github.com> wrote:

> Hi @prabjot678 https://github.com/prabjot678,
> 
> Thank for you reporting an issue and helping improve Kaltura!
> 
> To get the fastest response time, and help the maintainers review and test
> your reported issues or suggestions, please ensure that your issue includes
> the following (please comment with more info if you have not included all
> this info in your original issue):
> - Is the issue you're experiencing consistent and across platforms? or
>   does it only happens on certain conditions? please provide as much details
>   as possible.
> - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
>   If self hosted, are you using the RPM or deb install?
> - Packages installed. When using RPM, paste the output for:
>   
>   # rpm -qa \"kaltura*\"
> 
> For deb based systems:
> 
> ```
> # dpkg -l \"kaltura-*\"
> ```
> - If running a self hosted ENV - provide the MySQL server version used
> - If running a self hosted ENV - is this a single all in 1 server or a
>   cluster?
> - If running a self hosted ENV, while making the problematic request,
>   run:
>   
>   # tail -f /opt/kaltura/log/_.log /opt/kaltura/log/batch/_.log | grep -A 1 -B 1 --color \"ERR:|PHP|trace|CRIT|[error]\"
> 
> and paste the output.
> - When relevant, provide any screenshots or screen recordings showing
>   the issue you're experiencing.
> 
> For general troubleshooting see:
> 
> https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help
> 
> If you only have a general question rather than a bug report, please close
> this issue and post at:
> http://forum.kaltura.org
> 
> Thank you in advance,
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/issues/8#issuecomment-228827783,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHn8kURpvXlT9C1WQEPplCt5D8e_OcGFks5qQBImgaJpZM4I_VfL
> .

## 

[image: Oodles Technologies Pvt Ltd] http://www.oodlestechnologies.com/

_Prabjot Singh_  Software Developer, Oodles Technologies Pvt Ltd
Phone:   +91 124 4368 395
Mobile:   +91 9643042678 prabjot.singh@oodlestechnologies.com
Email:     prabjot.singh@oodlestechnologies.com
maneesh@oodlestechnologies.com
Website:  http://www.oodlestechnologies.com/
Skype:     prabjot678
Address: Unit No 951-955 , Tower B1, Spaze I-Tech Park , Sector 49 , Sohna
Road , Gurgaon , India , 122001
[image: Twitter] https://twitter.com/oodlestech [image: Facebook]
https://www.facebook.com/OodlesTech [image: Google +]
https://plus.google.com/+Oodlestechnologies/posts [image: LinkedIn]
https://www.linkedin.com/company/oodles-technologies-pvt-ltd

**Comment by jessp01** [comment]
Hello,
Please see my comment here: https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/issues/9
Thanks,
