### ISSUE TITLE
Facing error:MISSING_MANDATORY_PARAMETER,uploadTokenId

### ISSUE THREAD

**Issue by prabjot678** [kaltura/KalturaGeneratedAPIClientsNodeJS#9]
I am trying to upload file in kaltura using nodejs npm package 'kaltura', it is consistently showing me below error
<?xml version="1.0" encoding="utf-8"?><xml><result><error><objectType>KalturaAPIException</objectType><code>MISSING_MANDATORY_PARAMETER</code><message>Missing parameter &quot;uploadTokenId&quot;</message><args><item><objectType>KalturaApiExceptionArg</objectType><name>PARAM_NAME</name><value>uploadTokenId</value></item></args></error></result><executionTime>0.002338171005249</executionTime></xml>

So please help,why it is coming, i am using npm verison "kaltura": "^3.3.1",
I have posted question on stackoverflow,please find at 

http://stackoverflow.com/questions/38092408/kaltura-missing-mandatory-parameter-uploadtokenid 

to know error in details

**Comment by kaltura-hooks** [comment]
Hi @prabjot678,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa \"kaltura*\"
```

```
For deb based systems:
```

```
    # dpkg -l \"kaltura-*\"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi,

Sorry for the delay in response.
Please see full code samples here:
https://developer.kaltura.com/recipes/upload#

If it does not work for you, please post on forum.kaltura.org sharing your full code and I'll be happy to help you further.
